# age,name,sex,religon,ethnicity,height,degree
#there are 7 values

labels = ["age","name","sex","hobby","nationality","height","degree"]

profiles = profiles = [[21,"nathan","m","hockey","indian",5.3,"computer-science"],
            [20,"baro","m","climbing","indian",6.5,"maths"],
            [19,"Hanna","f","gym","german",5.1,"maths"],
            [18,"riza","f","piano","indian",4.5,"computer-science"],
            [17,"mohammed","m","tennis","indian",5.5,"computer-science"],
            [23,"hammna","f","hockey","italian",5.10,"computer-science"],
            [21,"boris","m","tennis","german",5.5,"maths"],
            [19,"rico","m","hockey","indian",5.11,"bio-chem"],
            [25,"maeze","f","piano","indian",6.2,"computer-science"],
            [20,"warren","m","tennis","german",5.5,"maths"],
            [18,"reuben","m","hockey","indian",5.7,"computer-science"],
            [19,"bubz","m","hockey","german",5.11,"bio-chem"],
            [22,"holly","f","gym","indian",5.3,"computer-science"],
            [19,"louis","m","hockey","italian",5.9,"maths"],
            [18,"rish","m","hockey","italian",5.4,"computer-science"],
            [19,"shophie","f","piano","indian",6.0,"maths"],
            [24,"phillip","m","piano","italian",6.1,"bio-chem"],
            [21,"musin","f","gym","indian",6.5,"computer-science"],
            [20,"jiwoo","f","hockey","italian",5.1,"computer-science"],
            [22,"anton","m","hockey","indian",5.6,"maths"],
            [18,"kota","m","gym","german",5.8,"bio-chem"],
            [19,"kush","m","hockey","italian",5.3,"computer-science"],
            [20,"tree","m","hockey","indian",5.2,"maths"],
            [19,"eda","f","climbing","indian",5.2,"computer-science"],
            [20,"sahitya","f","hockey","german",5.4,"computer-science"],
            [22,"bhavik","m","gym","german",5.10,"maths"],
            [19,"charles","m","piano","indian",5.4,"computer-science"],
            [23,"Luka","f","piano","german",5.11,"computer-science"],
            [19,"sophie","f","gym","italian",5.9,"bio-chem"],
            [21,"nathan","m","hockey","italian",5.2,"bio-chem"]]
